### ISSUE TITLE
[BUG] disabled-worlds didn't work.

### ISSUE THREAD

**Issue by xKsyStudio** [Binekrasik/CropsPlus#1]
**Describe the bug**
version1.2 have 'disabled-worlds' option
I tried setting him to world, but it didn't work.
There is something wrong with the plugin logic.
Also I recommend setting this to enable-world

**To Reproduce**
1. disabled-worlds:
  - world

**Desktop (please complete the following information):**
 - Minecraft server software and version: Paper1.19
 - Plugin version: 1.2

**Comment by Binekrasik** [comment]
Thanks for the bug report! Fixed in 1.2.1. I will also make a switch between enabled and disabled worlds, which will be implemented in future update.
